config/routes.rb
Rails.application.routes.draw do
  resources :tags
    devise_for :users
    
    resources :jobs, :companies
    root "jobs#index"
end

app/models/company.rb
class Company < ActiveRecord::Base
    
    
    belongs_to :user
    has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
    belongs_to :company
    
    has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    
    has_and_belongs_to_many :jobs
    
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :trackable, :validatable
    
    has_one :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    def index
        @companies = Company.all
    end
    
    def new
        @company = Company.new
    end
    
    def create
        @company = Company.new(company_params)
        @company.user_id = current_user.id
        if @company.save
            redirect_to @company, notice: "Vaga cadastrada"
        else
            render 'new'
        end
    end
    
    private
    
    def company_params
        params.require(:company).permit(:name, :image, :number_telephone, :description)
    end

    
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :find_job, only: [:show, :edit, :update, :destroy]
    
    def index
        @jobs = Job.all.order("created_at DESC")
    end
    
    def new
        @job = Job.new
    end

    def create
        @job = Job.new(job_params)
        @job.company_id = current_user.company.id
        
        if @job.save
            redirect_to @job, notice: "Vaga cadastrada"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @job.update(job_params)
            redirect_to @job, notice: "Vaga Atualizada"
        else
            render 'edit'
        end
    end
    
    def destroy
        @job.destroy
        redirect_to root_path
    end
    
    def show
    end
    
    private
    def job_params
        params.require(:job).permit(:title, :type_job, :description, :value, {:tag_ids => []})
    end
    
    
    
    def find_job
        @job = Job.find(params[:id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/companies/_form.html.haml
= simple_form_for @company, html: { multipart: true } do |f|
    - if @company.errors.any?
        #errors
            %h2
                = pluralize(@company.errors.count, "error")
                prevented this Pin from saving
            %ul
                - @company.errors.full_messages.each do |msg|
                    %li= msg
                    
    .form-group
        = f.input :name, input_html: { class: 'form-control'}, label: "Nome da empresa:"
      
    .form-group
        = f.input :image, input_html: { class: 'form-control'}, label: "Logo da empresa:"
     
    .form-group
        = f.input :number_telephone, input_html: { class: 'form-control'}, label: "Número de telefone:"
    
    .form-group
        = f.input :description, input_html: { class: 'form-control'}, label: "Descrição:"
    
    = f.button :submit, class: "btn btn-primary"

app/views/companies/index.html.haml
%h1 empresas

- @companies.each do |company|
    %h1= company.name

app/views/companies/new.html.haml
%h2 Digite seus dados:

= render 'form'

= link_to "Voltar", companies_path

app/views/jobs/_form.html.haml
= simple_form_for @job, html: { multipart: true } do |f|
    - if @job.errors.any?
        #errors
            %h2
                = pluralize(@job.errors.count, "error")
                prevented this Pin from saving
            %ul
                - @job.errors.full_messages.each do |msg|
                    %li= msg

    .form-group
        = f.input :title, input_html: { class: 'form-control'}, label: "Titulo"
    
    - if @job.id?
        .form-group
            = f.input :type_job, collection: ['Emprego', 'Estágio'], selected: @job.type_job, input_html: { class: 'form-control'}, label: "Tipo"
    - else
        .form-group
            = f.input :type_job, collection: ['Emprego', 'Estágio'], selected: "Emprego", input_html: { class: 'form-control'}, label: "Tipo"
    
    
    .form-group
        = f.input :description, input_html: { class: 'form-control'}, label: "Descrição"
    
    .form-group
        = f.association :tags, as: :check_boxes, label: "Tags"
   
    - if @job.id?
        .form-group
            = f.input :value, collection: ['Não definido', 'Até R$ 1 000,00', 'entre R$ 1 000,01 - R$ 2 000,00', 'entre R$ 2 000,01 - R$ 3 000,00', 'entre R$ 4 000,00 -  5 000,00', 'Acima de R$ 5 000,00'], selected: @job.value, input_html: { class: 'form-control'}, label: "Faixa salarial"
    - else
        .form-group
            = f.input :value, collection: ['Não definido', 'Até R$ 1 000,00', 'entre R$ 1 000,01 - R$ 2 000,00', 'entre R$ 2 000,01 - R$ 3 000,00', 'entre R$ 4 000,00 -  5 000,00', 'Acima de R$ 5 000,00'], selected: "Não definido", input_html: { class: 'form-control'}, label: "Faixa salarial"
            
    .form-group
        = f.button :submit, 'Salvar'

app/views/jobs/edit.html.haml
#h2 Editar vaga

= render 'form'

= link_to "Voltar", job_path

app/views/jobs/index.html.haml
.header_jobs
    .row
        .col-md-6
            %h1 Vagas
        .col-md-6
            %ul.nav.navbar-nav.navbar-right
                %li.filter_type.filter_type_estagio= link_to "Estagios", new_job_path
                %li.filter_type.filter_type_emprego= link_to "Empregos", new_job_path
                
%ul.vagas
    - @jobs.each do |job|
        %li.vaga
            .panel.panel-default.col-md-8.col-md-offset-2
                - if job.type_job == "Estágio"
                    .type_job.type_job_estagio
                - else
                    .type_job.type_job_emprego
                .panel-body
                    .row
                        .col-md-6
                            .titulo_vaga= link_to job.title, job
                            .valor_vaga
                                %span= job.value
                            %small= job.company.name
                        .col-md-6
                            - job.tags.each do |job_tag|
                                .tag
                                    %span.badge= job_tag.title

app/views/jobs/new.html.haml
New Form

= render 'form'

=link_to "Back", root_path

app/views/jobs/show.html.haml
%h3= @job.title

%p= @job.type_job

%p= @job.description

%p= @job.value


= link_to "Voltar", root_path
= link_to "Editar", edit_job_path
= link_to "Deletar", job_path, method: :delete, data: {confirm: "Tem certeza?"}

app/views/layouts/application.html.haml
%html
%body
    %title Trabalho Juridico
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
    %nav.navbar.navbar-default
        .container
            .navbar-brand= link_to "VagasJuris", root_path
            
            - if user_signed_in?
                %ul.nav.navbar-nav.navbar-right
                    %li
                        %span= current_user.email
                    %li= link_to "Cadastrar Vaga", new_job_path
                    %li= link_to "Sair", destroy_user_session_path, method: :delete
            - else
                %ul.nav.navbar-nav.navbar-right
                   
                    %li= link_to "Login", new_user_session_path
                    %li= link_to "Cadastrar", new_user_registration_path
    .container
        - flash.each do |name, msg|
            = content_tag :div, msg, class: "alert alert-info"

        = yield

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tag.title %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>